import React, { useMemo, useState } from "react";
import { AlertTriangle, BusFront, Camera, CheckCircle2, Clock3, Filter, Gauge, Layers3, MapPin, Search, SlidersHorizontal, X, Zap } from "lucide-react";
import { MapContainer, TileLayer, Marker, CircleMarker, Popup, useMap } from "react-leaflet";
import L from "leaflet";

const incidents=[
{id:101,camera_id:5,bus_id:"PMPML-207",event_type:"Pothole",severity:"High",confidence:.94,lat:18.531,lng:73.847,status:"Detected",timestamp:"10:35",location:"Shivajinagar"},
{id:102,camera_id:8,bus_id:"PMPML-118",event_type:"Congestion",severity:"Medium",confidence:.91,lat:18.501,lng:73.863,status:"In Progress",timestamp:"10:28",location:"Swargate"},
{id:103,camera_id:12,bus_id:"PMPML-142",event_type:"Waterlogging",severity:"High",confidence:.88,lat:18.536,lng:73.929,status:"Assigned",timestamp:"10:18",location:"Bann"},
{id:104,camera_id:4,bus_id:"PMPML-155",event_type:"Road Damage",severity:"Critical",confidence:.97,lat:18.507,lng:73.807,status:"Detected",timestamp:"10:12",location:"Kothrud"},
{id:105,camera_id:9,bus_id:"PMPML-091",event_type:"Infrastructure",severity:"Low",confidence:.86,lat:18.519,lng:73.855,status:"Resolved",timestamp:"09:54",location:"Camp"},
{id:106,camera_id:7,bus_id:"PMPML-231",event_type:"Pedestrian",severity:"Medium",confidence:.90,lat:18.478,lng:73.868,status:"Assigned",timestamp:"09:42",location:"Hadapsar"}
];
const buses=[{id:"PMPML-207",route:"27",speed:"31 km/h",status:"On route"},{id:"PMPML-118",route:"12",speed:"18 km/h",status:"Delayed"},{id:"PMPML-142",route:"45",speed:"24 km/h",status:"On route"}];
const iconFor=(kind)=>new L.DivIcon({className:"custom-map-icon",html:`<div class="map-pin ${kind.toLowerCase()}">${kind==="bus"?"●":"!"}</div>`,iconSize:[30,30],iconAnchor:[15,15]});
function MapCenter({point}){const map=useMap(); if(point) map.flyTo(point,14,{duration:.5}); return null;}
export default function Dashboard(){
 const [selected,setSelected]=useState(null),[query,setQuery]=useState(""),[type,setType]=useState("All"),[severity,setSeverity]=useState("All"),[status,setStatus]=useState("All"),[view,setView]=useState("markers"),[showFilters,setShowFilters]=useState(false),[updated,setUpdated]=useState(false);
 const filtered=useMemo(()=>incidents.filter(i=>(type==="All"||i.event_type===type)&&(severity==="All"||i.severity===severity)&&(status==="All"||i.status===status)&&`${i.event_type} ${i.location} ${i.bus_id}`.toLowerCase().includes(query.toLowerCase())),[query,type,severity,status]);
 const high=incidents.filter(i=>["High","Critical"].includes(i.severity)).length;
 return <main className="command-page">
  <div className="command-header"><div><div className="crumb">TRANSITEYE / COMMAND CENTER</div><h1>Urban Intelligence Dashboard</h1><p>Real-time mobility, road and safety intelligence from the connected fleet.</p></div><div className="header-actions"><span className="system-online"><i/> System Online</span><button className="outline-btn"><Zap size={15}/> Last sync 10:36</button></div></div>
  <div className="dashboard-stats">{[[AlertTriangle,"Total Incidents","128","+14 today",""],[Gauge,"High Severity",String(high),"Requires review","danger"],[BusFront,"Connected Buses","1,284","92% online",""],[CheckCircle2,"Resolved","74","58% of total","success"]].map(([Icon,label,value,sub,cl])=><div className="dash-stat" key={label}><span><Icon size={19}/></span><div><small>{label}</small><strong className={cl}>{value}</strong><em className={cl}>{sub}</em></div></div>)}</div>
  <div className="dashboard-workspace">
   <aside className={`filter-sidebar ${showFilters?"mobile-open":""}`}><div className="filter-head"><div><b>Filters</b><small>Refine urban events</small></div><button onClick={()=>setShowFilters(false)} className="mobile-close"><X size={17}/></button></div><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search location, bus..."/><Search size={15}/></label><Select label="Incident type" value={type} setValue={setType} options={["All","Pothole","Road Damage","Waterlogging","Congestion","Pedestrian","Infrastructure"]}/><Select label="Severity" value={severity} setValue={setSeverity} options={["All","Critical","High","Medium","Low"]}/><Select label="Status" value={status} setValue={setStatus} options={["All","Detected","Assigned","In Progress","Resolved"]}/><div className="filter-divider"/><div className="filter-summary"><span>Showing <b>{filtered.length}</b> of {incidents.length}</span><button onClick={()=>{setQuery("");setType("All");setSeverity("All");setStatus("All")}}>Reset</button></div><div className="legend-block"><b>Severity</b><span><i className="legend-dot critical"/>Critical</span><span><i className="legend-dot high"/>High</span><span><i className="legend-dot medium"/>Medium</span><span><i className="legend-dot low"/>Low</span></div></aside>
   <section className="map-panel"><div className="panel-head"><div><div className="panel-title"><MapPin size={17}/> Live GIS Map</div><small>Pune urban network · {filtered.length} active results</small></div><div className="map-tools"><button className={view==="markers"?"selected":""} onClick={()=>setView("markers")}><MapPin size={14}/> Markers</button><button className={view==="heatmap"?"selected":""} onClick={()=>setView("heatmap")}><Layers3 size={14}/> Heatmap</button><button className="filter-toggle" onClick={()=>setShowFilters(true)}><SlidersHorizontal size={15}/></button></div></div><div className="map-stage"><MapContainer center={[18.5204,73.8567]} zoom={11} scrollWheelZoom><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapCenter point={selected?[selected.lat,selected.lng]:null}/>{view==="markers"?filtered.map(i=><Marker key={i.id} position={[i.lat,i.lng]} icon={iconFor(i.severity)} eventHandlers={{click:()=>setSelected(i)}}><Popup><b>{i.event_type}</b><br/>{i.location}<br/>Confidence: {Math.round(i.confidence*100)}%</Popup></Marker>):filtered.map(i=><CircleMarker key={i.id} center={[i.lat,i.lng]} radius={10+i.confidence*10} pathOptions={{color:i.severity==="Critical"||i.severity==="High"?"#e34d4d":"#f2a23b",fillOpacity:.24,weight:2}} eventHandlers={{click:()=>setSelected(i)}}/>)}{buses.map((b,idx)=><Marker key={b.id} position={[[18.524,73.85],[18.512,73.864],[18.529,73.869]][idx]} icon={iconFor("bus")}><Popup><b>{b.id}</b><br/>Route {b.route} · {b.status}<br/>{b.speed}</Popup></Marker>)}</MapContainer><div className="map-legend-floating"><span><i className="legend-dot bus"/>Bus</span><span><i className="legend-dot high"/>Incident</span><span><i className="legend-dot medium"/>Medium</span></div></div></section>
   <aside className="event-panel"><div className="panel-head"><div><div className="panel-title">Recent Incidents</div><small>AI-detected events</small></div><span className="count-badge">{filtered.length}</span></div><div className="event-list">{filtered.map(i=><button key={i.id} onClick={()=>setSelected(i)} className={`event-row ${selected?.id===i.id?"selected":""}`}><span className={`event-icon ${i.severity.toLowerCase()}`}><AlertTriangle size={16}/></span><div className="event-main"><b>{i.event_type}</b><span><MapPin size={11}/>{i.location}</span><small><Clock3 size={11}/>{i.timestamp} · {i.bus_id}</small></div><div className="event-right"><strong>{Math.round(i.confidence*100)}%</strong><small>{i.status}</small></div></button>)}</div></aside>
  </div>
  {selected&&<IncidentDrawer incident={selected} onClose={()=>setSelected(null)} onUpdate={()=>setUpdated(true)}/>} {updated&&<div className="toast" onClick={()=>setUpdated(false)}><CheckCircle2 size={17}/> Status update queued for API sync.</div>}
 </main>
}
function Select({label,value,setValue,options}){return <label>{label}<select value={value} onChange={e=>setValue(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function IncidentDrawer({incident,onClose,onUpdate}){const [status,setStatus]=useState(incident.status);return <div className="drawer-backdrop" onClick={onClose}><aside className="incident-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className={`severity-pill ${incident.severity.toLowerCase()}`}>{incident.severity} severity</span><h2>{incident.event_type}</h2><p>{incident.location} · {incident.timestamp}</p></div><button className="close-btn" onClick={onClose}><X size={19}/></button></div><div className="evidence-placeholder"><Camera size={26}/><b>Evidence frame</b><span>Camera {incident.camera_id} · {incident.bus_id}</span></div><div className="detail-grid"><div><small>Confidence</small><b>{Math.round(incident.confidence*100)}%</b></div><div><small>Camera ID</small><b>CAM-{incident.camera_id}</b></div><div><small>Coordinates</small><b>{incident.lat}, {incident.lng}</b></div><div><small>Event ID</small><b>#{incident.id}</b></div></div><div className="timeline"><b>Status workflow</b>{["Detected","Assigned","In Progress","Resolved"].map((s,i)=><div className={s===status?"active":""} key={s}><span>{i+1}</span><div><strong>{s}</strong><small>{s===status?"Current status":"Workflow stage"}</small></div></div>)}</div><label className="drawer-select">Update status<select value={status} onChange={e=>setStatus(e.target.value)}>{["Detected","Assigned","In Progress","Resolved"].map(s=><option key={s}>{s}</option>)}</select></label><button className="primary-btn full-btn" onClick={onUpdate}>Save Status Update</button></aside></div>}
